### ISSUE TITLE
Launch with input file

### ISSUE THREAD

**Issue by shumsic** [arleypadua/PKHeX.Everywhere#91]
Wondering if there is a way to launch the website while passing it a save file as input? 
eg. https://pkhex-web.github.io/load?file=[PATH]

For my specific use case - using Apple Shortcuts, I’d like to have PKHeX Web open with some predetermined save file automatically loaded.

Understandable if this is not currently or ever possible. PKHeX Web has been amazing so far, thank you.

**Comment by arleypadua** [comment]
Thanks for the feedback. 

I already thought about that, web apps are not really allowed to access local file paths.

What would be possible is to pass a url instead of a path, but that wouldn't solve your use case.

The best option for your use case would be: https://github.com/santacrab2/PKHeXMAUI, but I'm aware only android builds are available, you'd need to build your own for iOS
